openapi: 3.0.3
info:
  title: Payment Gateway API
  description: High-performance API for processing secure financial transactions.
  version: 1.0.0
  contact:
    name: Fintech Engineering Team
    email: engineering@paymentgateway.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local Gateway
  - url: https://api.paymentgateway.com/v1
    description: Production Server

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      summary: Register a new merchant user
      operationId: register
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /auth/login:
    post:
      summary: Login to get a JWT token
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /payments:
    post:
      summary: Process a Payment
      description: Initiates a new payment transaction. Requires an idempotency key to prevent duplicate processing.
      operationId: processPayment
      parameters:
        - name: X-Idempotency-Key
          in: header
          required: true
          description: A unique UUID for this transaction. Used to ensure exactly-once processing in accordance with PCI-DSS compliance.
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
      responses:
        "201":
          description: Payment successfuly created and authorized.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "400":
          description: Invalid request payload.
        "402":
          description: Payment Required - Transaction declined by the acquiring bank.
        "409":
          description: Conflict - Duplicate idempotency key detected.
        "500":
          description: Internal Server Error.

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - merchantId
        - amount
        - currency
        - card
      properties:
        merchantId:
          type: string
          description: The unique identifier for the merchant.
          example: "MCH-789-XYZ"
        amount:
          type: number
          format: decimal
          description: The transaction amount.
          example: 99.99
        currency:
          type: string
          description: ISO 4217 3-letter currency code.
          example: "USD"
        card:
          $ref: "#/components/schemas/CardObject"
        description:
          type: string
          description: Optional transaction description.
          example: "Order #12345"

    CardObject:
      type: object
      required:
        - number
        - expiryMonth
        - expiryYear
        - cvv
      properties:
        number:
          type: string
          description: The 16-digit card number. Will be tokenized upon ingestion.
          example: "****-****-****-1234"
        expiryMonth:
          type: integer
          minimum: 1
          maximum: 12
          example: 12
        expiryYear:
          type: integer
          minimum: 2024
          example: 2028
        cvv:
          type: string
          description: Card verification value. Not stored after authorization.
          example: "***"

    PaymentResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: "8b7a0c10-2d3e-4f5a-6b7c-8d9e0f1a2b3c"
        status:
          type: string
          enum: [AUTHORIZED, CAPTURED, DECLINED, VOIDED]
          example: "AUTHORIZED"
        authorizationCode:
          type: string
          example: "AUTH123"
        timestamp:
          type: string
          format: date-time
          example: "2026-01-26T12:00:00Z"

    RegisterRequest:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
          example: "recruiter_test"
        password:
          type: string
          example: "password123"
        email:
          type: string
          example: "test@example.com"

    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "recruiter_test"
        password:
          type: string
          example: "password123"

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiJ9..."
        type:
          type: string
          example: "Bearer"
        username:
          type: string
          example: "recruiter_test"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
